### ISSUE TITLE
Alerts Indicator on Animal Record

### ISSUE THREAD

**Issue by cjrolfe** [SalesforceLabs/AnimalShelterStarter#154]
We have the Animal Alerts component, which shows all alerts, however, if the Animal Image component is used, it requires some scrolling down to see the alerts, and it has been asked if this can be made clearer.  Options

1. Move the Animal Alerts component up above the profile image
2. Look at a differently designed screen altogether
3. Create automation that when animal has active alerts an indicator is put in the Animal Highlights Panel, Flow + Formula Field?  

(Note on 3.  Flow would need to run when an Animal Alert is Created/Updated, but also needs to pickup when an alert has passed its End Date and is automatically inactive)

**Comment by GeekStewie** [comment]
Added the Badge Indicator and updated styling in v1.26 launched today.
