### ISSUE TITLE
Certain Flows are locked and unable to be edited/viewed

### ISSUE THREAD

**Issue by chad1737** [SalesforceLabs/AnimalShelterStarter#159]
**Describe the bug**
There are a handful of Flows that are unable to be opened or edited. Is this intentional? The majority of the Flows are _not_ like this, which is why I ask. 

**To Reproduce**
1. Go to Setup > Flows
2. Click on “Task - Update Future Movement Record on Task Completion” to attempt to pull it up. 
3. Error: nothing happens because the flow is locked.

**Expected behavior**
It should open up a new tab and allow for the admin user to read and edit the flow accordingly. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 122

**Comment by cjrolfe** [comment]
Working as designed as Managed Package.
Check to see if flows are all available as Templates

**Comment by GeekStewie** [comment]
Update 1.26 launched today resolves this as all flows are now marked as a Template.
