### ISSUE TITLE
Date Calculation Error

### ISSUE THREAD

**Issue by GeekStewie** [SalesforceLabs/AnimalShelterStarter#76]
Calculated Age is wonky with some dates. I checked the formula and I can see why (365 day years and 30 day months not always the case) but I also know age cals are a nightmare to get right, as it depends on how an organisation defines their month and day calcs (could vary). Maybe a decimal years-only value would be easier to deal with?

Test data if you need it:
DOB = 10th August 2021 shows 1 YEARS 0 MONTHS 0 DAYS
DOB = 11th August 2021 shows 0 YEARS 12 MONTHS 4 DAYS
…same pattern for a few days, reducing day count…
DOB = 15th August 2021 shows 0 YEARS 12 MONTHS 0 DAYS
DOB = 16th August 2021 shows 0 YEARS 11 MONTHS 29 DAYS

**Comment by cjrolfe** [comment]
Could try the following to account for Leap Years

IF(ISBLANK(Date_of_Birth__c), Estimated_Age__c, FLOOR((TODAY()-Date_of_Birth__c +1)/365.2425))
